#!/usr/bin/env python3
"""
WattBot 2025 - Python-based GCP Deployment
This script deploys WattBot to GCP without needing gcloud CLI
"""

import os
import sys
import subprocess
import time

# Configuration
PROJECT_ID = "wattbot-2025"
ZONE = "us-central1-a"
INSTANCE_NAME = "wattbot-vm"
MACHINE_TYPE = "n1-standard-8"

print("=" * 70)
print("WattBot 2025 - GCP Deployment")
print("=" * 70)
print()
print("Since gcloud CLI requires special permissions, let's use")
print("the Google Cloud Console web interface instead.")
print()
print("=" * 70)
print("AUTOMATED DEPLOYMENT INSTRUCTIONS")
print("=" * 70)
print()

print("📋 Step 1: Open Google Cloud Console")
print("-" * 70)
print(f"Open this URL in your browser:")
print(f"https://console.cloud.google.com/?project={PROJECT_ID}")
print()
input("Press Enter when you're in the Cloud Console...")

print()
print("🖥️  Step 2: Create the VM Instance")
print("-" * 70)
print("1. Click the menu (☰) → 'Compute Engine' → 'VM instances'")
print("2. Click 'CREATE INSTANCE'")
print("3. Configure the instance:")
print()
print(f"   Name: {INSTANCE_NAME}")
print(f"   Region: us-central1")
print(f"   Zone: {ZONE}")
print(f"   Machine type: {MACHINE_TYPE} (8 vCPUs, 30 GB memory)")
print()
print("4. Add GPU:")
print("   - Click 'CPU PLATFORM AND GPU'")
print("   - Click 'ADD GPU'")
print("   - GPU type: NVIDIA Tesla T4")
print("   - Number of GPUs: 1")
print()
print("5. Configure Boot Disk:")
print("   - Click 'CHANGE' under Boot disk")
print("   - Click 'Custom images' or 'Public images'")
print("   - Operating System: Deep Learning on Linux")
print("   - Version: Debian 11 based Deep Learning VM")
print("   - Boot disk type: Standard persistent disk")
print("   - Size: 100 GB")
print("   - Click 'SELECT'")
print()
print("6. Click 'CREATE' at the bottom")
print()
input("Press Enter after you've created the VM...")

print()
print("⏳ Step 3: Wait for VM to Start")
print("-" * 70)
print("The VM will take 2-3 minutes to fully boot up.")
print("Wait until you see a green checkmark next to the instance.")
print()
input("Press Enter when the VM is running...")

print()
print("📤 Step 4: Upload Files to VM")
print("-" * 70)
print("1. In the VM instances list, click 'SSH' next to your VM")
print("2. A terminal window will open in your browser")
print()
print("3. In that terminal, run these commands:")
print()
print("   " + "=" * 60)
print("   # Create directory structure")
print("   mkdir -p ~/wattbot2025/data/{raw,chunks,processed,cache}")
print("   cd ~/wattbot2025")
print()
print("   # Install dependencies")
print("   python3 -m pip install --upgrade pip")
print("   python3 -m pip install pandas numpy python-dotenv pyyaml tqdm \\")
print("       google-generativeai sentence-transformers rank-bm25 \\")
print("       torch transformers scikit-learn")
print("   " + "=" * 60)
print()
input("Press Enter after running the above commands...")

print()
print("4. Now we need to upload your files.")
print("   In the SSH window, look for the 'Upload file' option (gear icon)")
print("   Or use this simpler method:")
print()
print("   " + "=" * 60)
print("   # Create a simple upload script")
print("   cat > upload_files.sh << 'EOF'")

# Generate the upload instructions
project_root = "/Users/revanshphull/watt/wattbot2025"

print("#!/bin/bash")
print("# This will be filled with your files")
print("EOF")
print("   " + "=" * 60)
print()

print()
print("💡 EASIER METHOD - Use Cloud Shell to Upload")
print("-" * 70)
print("1. Open Cloud Shell (click >_ icon at top of Cloud Console)")
print("2. In Cloud Shell, run:")
print()
print("   " + "=" * 60)
print("   # Clone or upload your repo")
print(f"   # Then copy to VM:")
print(f"   gcloud compute scp --recurse ~/wattbot2025 {INSTANCE_NAME}:~/ --zone={ZONE}")
print("   " + "=" * 60)
print()

print()
print("🚀 Step 5: Run the Pipeline")
print("-" * 70)
print("Back in your VM's SSH terminal, run:")
print()
print("   " + "=" * 60)
print("   cd ~/wattbot2025")
print("   python3 run.py")
print("   " + "=" * 60)
print()
print("The pipeline will start running!")
print()
input("Press Enter to see download instructions...")

print()
print("📥 Step 6: Download Results (After Pipeline Completes)")
print("-" * 70)
print("1. In the SSH terminal, check if results exist:")
print("   ls -lh ~/wattbot2025/data/processed/submission.csv")
print()
print("2. Download via SSH window's download feature")
print("   Or use Cloud Shell:")
print()
print("   " + "=" * 60)
print(f"   gcloud compute scp {INSTANCE_NAME}:~/wattbot2025/data/processed/submission.csv . --zone={ZONE}")
print("   " + "=" * 60)
print()

print()
print("🗑️  Step 7: DELETE THE VM (Important!)")
print("-" * 70)
print("Don't forget to delete the VM to avoid charges!")
print()
print("1. Go back to 'Compute Engine' → 'VM instances'")
print(f"2. Check the box next to '{INSTANCE_NAME}'")
print("3. Click 'DELETE' at the top")
print("4. Confirm deletion")
print()
print("Estimated cost for this run: $0.10 - $0.20")
print()

print("=" * 70)
print("Deployment guide complete!")
print("=" * 70)
print()
print("For direct file upload from your Mac, I'll create a separate")
print("script that handles the permission issues...")
